steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      # API URL 빌드 인자
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      # ✨ WebSocket URL 빌드 인자 추가
      - '--build-arg'
      - 'NEXT_PUBLIC_WEBSOCKET_URL=${_NEXT_PUBLIC_WEBSOCKET_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/surfai-frontend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/surfai-frontend:latest']
images:
  - 'gcr.io/$PROJECT_ID/surfai-frontend:latest'