steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_WEBSOCKET_URL=${_NEXT_PUBLIC_WEBSOCKET_URL}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/surfai-frontend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/surfai-frontend:latest']
images:
  - 'gcr.io/${PROJECT_ID}/surfai-frontend:latest'